### ISSUE TITLE
The module RCA and sub is missing

### ISSUE THREAD

**Issue by ducklingQQ** [weihangtan/Modular-multiplier#1]
Thank you for sharing. However, when I try to synthesize your design with 60-bit q for comparison, I find that the modules RCA and sub cannot be found.  Expect this issue to be fixed.

**Comment by weihangtan** [comment]
Thank you for reaching out. These two files have been uploaded, and please let me know if there is any other problem.

**Comment by ducklingQQ** [comment]
Thanks :)
